### PR TITLE
Add ability to turn off validation of max size

### LINKED ISSUE #8: Allow for argument to validate or not
Hi! Would a PR with an additional argument overload after `delimiterForSats` that would enable or disable `checkMaxSatoshis` be approved? It would make the library useable for blockchains other than Bitcoin and it would solve #5 who is asking for negative value support. We're building tooling for Bitcoin and many other Bitcoin-protocol-based chains and need this additional feature. We can fork and make our own release if this library want to stay focused only on Bitcoin. Thanks!

### PR DESCRIPTION
**Pull request by sondreb**
- Add an argument to the library allowing chains that have different rules than Bitcoin to use the library.
- Closes #8

### CODE REVIEW

**Comment by afizzycola** [comment]
Hi @sondreb. Thanks for this, all looks good. I was wondering if you required the left hand side of the "." to also be formatted (e.g. with commas) as per the discussion on [twitter](https://twitter.com/dangershony/status/1456217761378619393).
Was thinking of making the 2nd parameter of each method an options object which could look like
```javascript
{
   rhsDelimiter: string,
   lhsDelimiter: string,
   bitcoinMaxSupplyValidation: boolean
}
```
It would be a breaking change to the library but as you are the first to probably use the library in anger then I think its an acceptable change which would cater for future config needs.

Thoughts?

**Comment by sondreb** [comment]
Right-hand formatting is done separately in our use-case, but maybe it could be added to satcomma, good idea.

I was also thinking we should change the methods to use a configuration object as oppose to arguments, it becomes a mess quickly with parameters and function signatures changes every time we need to extend it. So taking the breaking change now before wide use is good.

I'll update this PR :)

**Comment by afizzycola** [comment]
@sondreb were you able to have a look at updating the PR with this config/options object? If not I might have a go myself :)

**Comment by sondreb** [comment]
If you can do it, please go ahead =) I have not had the time yet and won't until next week.

**Comment by afizzycola** [comment]
No worries will have a look at this over the next few days

**Pull request merged**
